/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TonKhoRouteImport } from './routes/ton-kho'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as PhieuSuaChuaRouteImport } from './routes/phieu-sua-chua'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KhachHangRouteImport } from './routes/khach-hang'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CuaHangRouteImport } from './routes/cua-hang'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const TonKhoRoute = TonKhoRouteImport.update({
  id: '/ton-kho',
  path: '/ton-kho',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PhieuSuaChuaRoute = PhieuSuaChuaRouteImport.update({
  id: '/phieu-sua-chua',
  path: '/phieu-sua-chua',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KhachHangRoute = KhachHangRouteImport.update({
  id: '/khach-hang',
  path: '/khach-hang',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CuaHangRoute = CuaHangRouteImport.update({
  id: '/cua-hang',
  path: '/cua-hang',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/cua-hang': typeof CuaHangRoute
  '/dashboard': typeof DashboardRoute
  '/khach-hang': typeof KhachHangRoute
  '/login': typeof LoginRoute
  '/phieu-sua-chua': typeof PhieuSuaChuaRoute
  '/setup': typeof SetupRoute
  '/ton-kho': typeof TonKhoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/cua-hang': typeof CuaHangRoute
  '/dashboard': typeof DashboardRoute
  '/khach-hang': typeof KhachHangRoute
  '/login': typeof LoginRoute
  '/phieu-sua-chua': typeof PhieuSuaChuaRoute
  '/setup': typeof SetupRoute
  '/ton-kho': typeof TonKhoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/cua-hang': typeof CuaHangRoute
  '/dashboard': typeof DashboardRoute
  '/khach-hang': typeof KhachHangRoute
  '/login': typeof LoginRoute
  '/phieu-sua-chua': typeof PhieuSuaChuaRoute
  '/setup': typeof SetupRoute
  '/ton-kho': typeof TonKhoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/cua-hang'
    | '/dashboard'
    | '/khach-hang'
    | '/login'
    | '/phieu-sua-chua'
    | '/setup'
    | '/ton-kho'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/cua-hang'
    | '/dashboard'
    | '/khach-hang'
    | '/login'
    | '/phieu-sua-chua'
    | '/setup'
    | '/ton-kho'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/cua-hang'
    | '/dashboard'
    | '/khach-hang'
    | '/login'
    | '/phieu-sua-chua'
    | '/setup'
    | '/ton-kho'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CuaHangRoute: typeof CuaHangRoute
  DashboardRoute: typeof DashboardRoute
  KhachHangRoute: typeof KhachHangRoute
  LoginRoute: typeof LoginRoute
  PhieuSuaChuaRoute: typeof PhieuSuaChuaRoute
  SetupRoute: typeof SetupRoute
  TonKhoRoute: typeof TonKhoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ton-kho': {
      id: '/ton-kho'
      path: '/ton-kho'
      fullPath: '/ton-kho'
      preLoaderRoute: typeof TonKhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phieu-sua-chua': {
      id: '/phieu-sua-chua'
      path: '/phieu-sua-chua'
      fullPath: '/phieu-sua-chua'
      preLoaderRoute: typeof PhieuSuaChuaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khach-hang': {
      id: '/khach-hang'
      path: '/khach-hang'
      fullPath: '/khach-hang'
      preLoaderRoute: typeof KhachHangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cua-hang': {
      id: '/cua-hang'
      path: '/cua-hang'
      fullPath: '/cua-hang'
      preLoaderRoute: typeof CuaHangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  CuaHangRoute: CuaHangRoute,
  DashboardRoute: DashboardRoute,
  KhachHangRoute: KhachHangRoute,
  LoginRoute: LoginRoute,
  PhieuSuaChuaRoute: PhieuSuaChuaRoute,
  SetupRoute: SetupRoute,
  TonKhoRoute: TonKhoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
